# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 12:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allele',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repeats', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Fragment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dye', models.CharField(max_length=8)),
                ('size', models.FloatField()),
                ('height', models.IntegerField()),
                ('area', models.IntegerField()),
                ('qual', models.CharField(max_length=8)),
                ('score', models.IntegerField()),
                ('comments', models.CharField(max_length=256)),
                ('allele', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HD.Allele')),
            ],
        ),
        migrations.CreateModel(
            name='GeneMarker_xls_export',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xls_file', models.FileField(upload_to='xls_files/%Y%m%d')),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_number', models.CharField(max_length=12, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Well',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('well_name', models.CharField(max_length=8)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HD.Sample')),
            ],
        ),
        migrations.CreateModel(
            name='Worksheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ws_number', models.CharField(max_length=16, unique=True)),
                ('datetime', models.DateTimeField(null=True, unique=True)),
                ('panel', models.CharField(max_length=32)),
                ('size', models.CharField(max_length=16)),
                ('analysis_type', models.CharField(max_length=32)),
                ('software', models.CharField(max_length=128)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.AddField(
            model_name='well',
            name='worksheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HD.Worksheet'),
        ),
        migrations.AddField(
            model_name='fragment',
            name='well',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HD.Well'),
        ),
    ]
