# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 10:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Well',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('well_name', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Worksheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ws_number', models.CharField(max_length=16, unique=True)),
                ('datetime', models.DateTimeField()),
                ('panel', models.CharField(max_length=32, unique=True)),
                ('size', models.CharField(max_length=16, unique=True)),
                ('analysis_type', models.CharField(max_length=32, unique=True)),
                ('software', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='well',
            name='worksheet_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HD.Worksheet'),
        ),
    ]
