# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HD', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksheet',
            name='datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
