# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HD', '0002_auto_20170818_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksheet',
            name='analysis_type',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='datetime',
            field=models.DateTimeField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='panel',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='size',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='software',
            field=models.CharField(max_length=128),
        ),
    ]
