# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 14:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HD', '0003_auto_20170818_1127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='well',
            old_name='worksheet_id',
            new_name='worksheet',
        ),
    ]
